spring:
  profiles: stg
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
#    url: jdbc:h2:file:/tmp/testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
flyway:
  enabled: false
#server.port: 0